name: Deploy - PROD
on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml

  deploy-dev:
    name: "🚀 Prod"
    needs: build
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/deploy.yml
    with:
      env: prod
      artifact: ${{ needs.build.outputs.artifact-name }}
      sku: "B1"
      build-id: "prod"
