name: 🎡 Deploy - DEV
on:
  push:
    tags-ignore:
      - "v[0-9]+.[0-9]+.[0-9]+"
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build
    uses: ./build.yml@main

  deploy-dev:
    name: "🚀 Dev"
    needs: build
    permissions:
      id-token: write
      contents: read
    uses: ./deploy.yml@main
    with:
      ENV: dev
      ARTIFACT: ${{ needs.build.outputs.artifact-name }}
      SKU: "B1"
      build-id: "dev"
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      API_CLIENT_ID: ${{ secrets.API_CLIENT_ID }}
      #FUNC_PUBLISH_PROFILE: ${{ secrets.FUNC_PUBLISH_PROFILE }}
